baseURL: "http://javeronis.com/"
languageCode: "en-us"
title: Homepage
theme: DoIt
enableEmoji: true
languages:
  en:
    weight: 1
    languageCode: "en"
    languagename: "English"
    menu:
      main:
        - identifier: "posts"
          name: "Posts"
          url: "/posts/"
          weight: 1
    
params:
  version: "0.2.X"
  title: Dominic Benintendi
  description: "Hello World"
  defaultTheme: "auto"
  dateFormat: "01-02-2006"
  images: ["content/assets/pfp.jpg"]
  header:
    desktopMode: "fixed"
    mobileMode: "auto"
    title:
      name: "Dom's Domicile"
  footer:
    enable: false
  home:
    profile:
      enable: true
      avatarURL: "/assets/pfp.jpg"
      title: "Dominic Benintendi"
      subtitle: "Software Engineer and Local Computer Wizard, Studied at Ohio University for Computer Science and Eletrical Enginnering"
      social: true
    posts:
      enable: true
      paginate: 6
  social:
    GitHub: "DominicBen"
    Linkedin: "dominic-benintendi-023756179"
    Instagram: "dominic.benintendi"
    Twitter: ""
    Youtubechannel: ""
