baseURL: "https://javeronis.com"
languageCode: "en-us"
title: Homepage
theme: DoIt
enableEmoji: true

menu:
  main:
    - identifier: "posts"
      pre: ""
      post: ""
      name: "Posts"
      url: "/posts/"
      title: ""
      weight: 1
    - identifier: "resume"
      pre: ""
      post: ""
      name: "Resume"
      url: "/resume.pdf"
      title: ""
      weight: 2

languages:
  en:
    weight: 1
    languageCode: "en"
    languagename: "English"

params:
  version: "0.2.X"
  title: Dominic Benintendi
  description: "My personal website"
  defaultTheme: "auto"
  dateFormat: "01-02-2006"
  images: ["assets/2025Headshot.jpg"]
  
  author:
    name: "Dominic"
    email: "bdominic00@gmail.com"
    avatar: "assets/pfp.webp"

  page:
    author: true

  header:
    desktopMode: "fixed"
    mobileMode: "auto"
    title:
      name: "Dominic's Website"

  footer:
    enable: false

  home:
    profile:
      enable: true
      avatarURL: "https://media.licdn.com/dms/image/v2/D5603AQFcEa5M8bHjVA/profile-displayphoto-shrink_800_800/B56ZY25f1vHQAg-/0/1744677764889?e=1750291200&v=beta&t=K2rtHnq9LnB1lA_YHJ4SnnSWumtl1gc1sC_8y48cMjs"
      title: "Dominic Benintendi"
      subtitle: "Studied at Ohio University for Computer Science and Electrical Engineering. Born and raised in Ohio."
      social: true
    posts:
      enable: true
      paginate: 6

  social:
    GitHub: "DominicBen"
    Linkedin: "dominic-benintendi-023756179"
    Instagram: "dominic.benintendi"
    Twitter: ""
    Youtubechannel: ""
