baseURL: "https://javeronis.com"
languageCode: "en-us"
title: Homepage
theme: DoIt
enableEmoji: true

menu:
  main:
    - identifier: "posts"
      pre: ""
      post: ""
      name: "Posts"
      url: "/posts/"
      title: ""
      weight: 1
    - identifier: "resume"
      pre: ""
      post: ""
      name: "Resume"
      url: "/resume.pdf"
      title: ""
      weight: 2
    # - identifier: "about"
    #   pre: ""
    #   post: ""
    #   name: "About"
    #   url: "/about/"
    #   title: ""
    #   weight: 2
    #
languages:
  en:
    weight: 1
    languageCode: "en"
    languagename: "English"

params:
  version: "0.2.X"
  title: Dominic Benintendi
  description: "My personal website"
  defaultTheme: "auto"
  dateFormat: "01-02-2006"
  images: ["assets/2025Headshot.jpg"]
  
  author:
    name: "Dominic"
    email: "bdominic00@gmail.com"
    avatar: "assets/pfp.webp"

  page:
    author: true

  header:
    desktopMode: "fixed"
    mobileMode: "auto"
    title:
      name: "Dominic's Website"

  footer:
    enable: false

  home:
    profile:
      enable: true
      avatarURL: "assets/2025Headshot.jpg"
      title: "Dominic Benintendi"
      subtitle: "Majored in Computer Science and Electrical Engineering at Ohio University"
      social: true
    posts:
      enable: true
      paginate: 6

  social:
    GitHub: "DominicBen"
    Linkedin: "dominic-benintendi-023756179"
    Instagram: "dominic.benintendi"
    Twitter: ""
    Youtubechannel: ""
